# Generated by Django 4.1 on 2023-03-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_amo',
            field=models.BooleanField(default=False),
        ),
    ]
