# Generated by Django 4.1 on 2023-03-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_in_amo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_min',
            field=models.IntegerField(default=0),
        ),
    ]
