# Generated by Django 4.1 on 2023-03-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
